# Generated by Django 6.0 on 2025-12-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RzN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='power',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
